name: Release

on:
  workflow_dispatch:
    inputs:
      tag:
        description: Release Tag format is Semver, input "vX.Y.Z"
        required: true
        type: string
      
jobs:
  build:
    if: ${{ github.event.inputs.tag }} =~ ^v(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Build Go
        shell: pwsh
        run: |
          go install github.com/google/go-licenses@latest
          go-licenses save ./... --force --save_path ./build/licenses
          go build -o ./build/FileLock.exe -ldflags "-s -w -X=main.version=${{ github.event.inputs.tag }}" -trimpath
          Compress-Archive -Path .\build\* -Destination .\build\FileLock_${{ github.event.inputs.tag }}.zip
      - name: GitHub Release
        run: |
          gh release create ${{ github.event.inputs.tag }} FileLock_${{ github.event.inputs.tag }}.zip --generate-notes --title ${{ github.event.inputs.tag }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
